FROM python:3.6-alpine
RUN mkdir /app
WORKDIR /app
COPY . .
RUN apk add --no-cache --virtual .build-deps \
    && pip install -r requirements.txt

CMD [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]